name: node-gs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  build:
    name: build
    env:    
      JOBENV: build
      
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.17.0]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm test

  
  e3-promote:
    name: Promote to Production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: echo "promoting code to Production environment"
    - run: echo "**e3-promote execution status:success"
